### ISSUE TITLE
Offer to help

### ISSUE THREAD

**Issue by rob-luke** [hoechenberger/mne-installers#10]
Hi @hoechenberger,

I think this project is great and would love to help. I just ran the installer on my Mac and ran `source ~/mne-python/bin/activate` and indeed I could run mne-python v0.23.0!

I also have access to linux and windows pc's in the office, so I can test on those for you too.

You mentioned in the mne-python chat that adding a start menu item was possible. I think this would be a great feature for new users.

A few extra features (that you probably already have planned, I know its early days 😄 ):
* Instructions on how to install packages on top of this installer. E.g. MNE-NIRS
* Instructions on how to start clean if the environment stops working. This is the most common issue I face with users.

Please let me know anyway I can help,
Rob

**Comment by hoechenberger** [comment]
Thanks for giving it a shot, @rob-luke!

> You mentioned in the mne-python chat that adding a start menu item was possible. I think this would be a great feature for new users.

So this would be based on [menuinst](https://github.com/conda/menuinst). The [Spyder feedstock](https://github.com/conda-forge/spyder-feedstock/tree/master/recipe) makes use of it, adding 2 menu entries on Windows (check `menu-windows.json`, `meta.yaml`, and `bld.bat`)
We'd need to adjust the [`mne` feedstock](https://github.com/conda-forge/mne-feedstock) in a similar manner to get menus. (This also means that the menus will be available for users who manually run `conda install -c conda-forge mne` on Windows, too – not just for those who use our installer)

I've never worked with `menuinst` myself – if you have time, feel free to play with it!

> * Instructions on how to install packages on top of this installer. E.g. MNE-NIRS

I'd love to aim for an installer where users typically will not have to install anything manually. That said, I think we should include MNE-NIRS in the installer. Do you want to make a PR for this? Is MNE-NIRS already on `conda-forge`? If not, that's the first thing we'll need to address :)


> * Instructions on how to start clean if the environment stops working. This is the most common issue I face with users.

On Windows the installers are supposed to add an uninstall entry to Programs and Features. But as I don't have a Windows machine, I couldn't test this. In fact, I tested nothing on Windows so far. CI also doesn't install & test the generated Windows installer.

I think (manual and automated) testing on Windows is what is most urgently needed at this stage. The Windows installer will also need MNE logos (#4, see https://github.com/conda/constructor/blob/master/CONSTRUCT.md#welcome_image and https://github.com/conda/constructor/tree/master/examples/maxiconda for an example).

So yeah, there's many things to do – pick whatever you like! Your help will be greatly appreciated! As for instructions on how to install arbitrary packages, I'd postpone this for now.

Let me know what you think, I'm also very happy to chat!

Best,

Richard

**Comment by rob-luke** [comment]
> Is MNE-NIRS already on conda-forge? If not, that's the first thing we'll need to address :)

It is now, but I am happy to add it. Actually I think the first thing I need to do is inform myself about conda, mamba, pypi, etc and how they are all related. I will do some reading tonight. I managed to get pypi working, so Im sure Ill get this up. I will ping back here once its up.

> pick whatever you like

If I get a chance to tackle an item I will assign myself to the issue first, as not to duplicate effort. But first Ill tackle the conda issue for MNE-NIRS.

> Let me know what you think

Brilliant. Getting MNE installed seems to be the biggest barrier I have had to getting people to take up MNE-NIRS, so if we can make this a simple double click that would be awesome.

**Comment by hoechenberger** [comment]
btw apparently, `menuinst` can create links to websites too. So we could e.g. add a menu entry pointing to the MNE documentation:

https://github.com/conda/menuinst/wiki/Menu-Shortcut-Config-Structure

**Comment by hoechenberger** [comment]
> Actually I think the first thing I need to do is inform myself about conda, mamba, pypi, etc and how they are all related.

It can be complicated :) Especially since `conda-forge` has some particularities as well. Maybe you should start with skimming over some `conda-forge` docs? https://conda-forge.org/docs/

**Comment by rob-luke** [comment]
Thanks for the links!

**Comment by hoechenberger** [comment]
@rob-luke Thinking back of how long it took me to "get" conda / conda-forge, maybe it could make sense if we schedule a screenshare session and I talk you through some basics / we do them together? Ping me on Discord :)
