### ISSUE TITLE
Add "base" installers too

### ISSUE THREAD

**Issue by hoechenberger** [hoechenberger/mne-installers#28]
Should only include `mne-base`, `matplotlib`, and probably `jupyter` or so? What else would be needed for a "basic" installation?

cc @agramfort @larsoner

**Comment by larsoner** [comment]
To me it's a low priority, a minimal env is probably bit so useful for *users*, which is the target audience for the installers. Having few requirements is more useful for downstream packages/devs or advanced users who probably aren't going to use our standalone installers anyway I think

**Comment by hoechenberger** [comment]
Good point, I'll move this down on my priorities list unless @agramfort disagrees
