### ISSUE TITLE
Include MNE "sample" data (or provide it in a separate installer)?

### ISSUE THREAD

**Issue by hoechenberger** [hoechenberger/mne-installers#32]
I realized that when you want to try out your shiny new MNE after successful installation, running our tutorials will start downloading the `sample` data, making the installers only semi-usable for offline use.

I'm wondering if we could include our MNE datasets (or at least `sample`) in the installers, or at least provide separate installers for them. I was thinking we could actually make an `mne-data` conda package.

Similarly, we could package add the HTML documentation.

WDYT?

cc @larsoner

**Comment by larsoner** [comment]
Definitely not as part of the main installer, it adds 1-2GB. I would just live with `mne.datasets.sample.data_path()` being the preferred way to get any data, including sample. I don't hear any complaints from people about this process, so I don't think it's a high priority to make it easier for people to get the sample data.

I wouldn't even make on offline installer, I would tell people "download this .tar.gz and put it in ~/mne_data" then I think it will just work...

**Comment by agramfort** [comment]
yes it's too big. Let them download it with our fetcher
