### ISSUE TITLE
Make mne-qt-browser the default plotting engine

### ISSUE THREAD

**Issue by hoechenberger** [hoechenberger/mne-installers#36]
We can inject environment variables into the created environment upon activation, so all we'd need to do is set

```console
MNE_BROWSER_BACKEND=pyqtgraph
```
This can be achieved via a modification to `construct.yaml`

@agramfort @larsoner @marsipu I'm quite determined to make this change, unless this idea gives you a terrible stomach ache..? I want to increase visibility of Martin's amazing new backend that way. I would bet many users aren't even aware it exists.

**Comment by agramfort** [comment]
fine with me if it works out of the box !

**Comment by larsoner** [comment]
I think mne-installers shouldn't deviate from standard MNE... whether or not we should change the default for 1.0 we should discuss tomorrow probably

**Comment by cbrnr** [comment]
Would making the new browser make PyQt/PySide packages mandatory requirements? On macOS, I like using the `osx` backend because I don't need to have PyQt/PySide installed. Ideally, I would like to still be able to do `raw.plot()` with just `matplotlib` installed.

**Comment by hoechenberger** [comment]
> Would making the new browser make PyQt/PySide packages mandatory requirements?

My understanding is that we'll only use the `mne-qt-browser` if it's installed, like we do now. The difference is that currently, just installing it is not enough; you also have to explicitly tell MNE-Python to actually make use of it.

**Comment by cbrnr** [comment]
Ah OK, this sound good!

**Comment by larsoner** [comment]
Yes I just merged it in https://github.com/mne-tools/mne-python/pull/9960 !

**Comment by hoechenberger** [comment]
Perfect, thanks!
