### ISSUE TITLE
Update to 1.0?

### ISSUE THREAD

**Issue by larsoner** [hoechenberger/mne-installers#50]
Any reason all builds are currently named 0.24? It seems like they should be 1.0.dev0 or so, since that's what they need to work with...?

**Comment by hoechenberger** [comment]
It's very simple: The `constructor` we use to create the installers currently only supports `conda` packages*, and there's no `mne-dev` package, so I'm using the latest `mne` stable package from `conda-forge` for now.

My proposal is: we build a (nightly? 4-hourly?) `conda` package of `mne-python:main` on this CI system which can be used in subsequent CI runs for building the installer.

Or … maybe better, we do that build inside our regular GH action for building the installer; we cache created devel package and set the cache timeout to 1 day or so, and only regenerate when the cache is empty. WDYT?


*this is only true when specifying the dependencies of the installer in the `spec` section of `construct.yaml`; if using an `environment.yml` file instead, one **can** indeed use `pip`-installed packages. However, this comes with other problems that I'd like to avoid (namely, `conda` then somehow loses track of the actual source of all packages – it thinks they **all** came from PyPI. It's a weird bug)

**Comment by hoechenberger** [comment]
@larsoner Actually we'd also need to build devel packages for MNE-BIDS etc then. All very possible. But it highlights some complications!

**Comment by hoechenberger** [comment]
> Or … maybe better, we do that build inside our regular GH action for building the installer; we cache the created `mne-dev` package and set the cache timeout to 1 day or so, and only regenerate when the cache is empty. WDYT?

Maybe an even better idea would be to upload the packages to `anaconda.org`:
https://docs.anaconda.com/anacondaorg/user-guide/tasks/work-with-packages/#uploading-packages

We could have an `mne-devel` branch or something and drop MNE-Python, MNE-BIDS etc. there.

**Comment by hoechenberger** [comment]
> Maybe an even better idea would be to upload the packages to `anaconda.org`:

I'll start working on this tomorrow or Monday.

**Comment by larsoner** [comment]
Hmm... not sure it's worth doing nightly builds. I mostly meant that these installers need to work with the 1.0 release when it comes out. To me it makes sense to just make sure these installers work in the weeks leading up to release time so that once we cut a release, we can build the installers quickly (like within a day) before we send out the release email.

I don't think people who want to use latest MNE-Python `main` should use these installers. Also I think it will require a lot of (really unnecesary) work to keep nightly builds working all the time. So I think we should just put this effort in at release time rather than continuously.

**Comment by hoechenberger** [comment]
Good point. I'll add dev builds on conda-forge then for all relevant packages, with the build triggered manually. Then we can start using them in installer.

**Comment by hoechenberger** [comment]
I've started working on this at https://github.com/conda-forge/mne-feedstock/pull/63

@larsoner How should we deal with the fact that we kind of have a circular dependency, in where we'd want `mne` to depend on `mne-qt-browser`, however `mne-qt-browser` itself needs `mne`?

**Comment by hoechenberger** [comment]
MNE-BIDS devel now done too, will be available from `conda-forge/label/mne-bids_dev`
